/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Bar */

#ifndef _Included_com_example_Bar
#define _Included_com_example_Bar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Bar
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_Bar_nativeMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
